global proc WTAutoBodyFileMake()  
{
	if (`window -exists "WTAutoBodyFileMakewindow"`)
	{
		deleteUI -window "WTAutoBodyFileMakewindow";
	}
	window -title "WT Rig All 相关文件制作" -h 530 -w 405 -rtf 1 -s 0 -tlb 0 WTAutoBodyFileMakewindow;



}
//预设文件写入
global proc writeFile ( string $filename, string $addcontents )
{
	$fileId=`fopen $filename "a"`;
	fprint $fileId ( $addcontents );
	fclose $fileId;
}

//预设文件清空
global proc cleanFile ( string $cfilename )
{
	$cfileId=`fopen $cfilename "w"`;
	fprint $cfileId "";
	fclose $cfileId;
}
//导出连接
global proc ExportConnection( string $SourceObject , string $ExportPath )
{
	string $CurrentConnectionpFrom[] = `listConnections -s 1 -d 0 -c 1 -p 1 $SourceObject`;
	string $CurrentConnectionpFromText = stringArrayToString($CurrentConnectionpFrom , "\n");
	string $CurrentConnectionpTo[] = `listConnections -s 0 -d 1 -c 1 -p 1 $SourceObject`;
	string $CurrentConnectionpToText = stringArrayToString($CurrentConnectionpTo , "\n");
	string $ExportFromFile = $ExportPath + "/" + $SourceObject + ".from";
	string $ExportToFile = $ExportPath + "/" + $SourceObject + ".to";
	if (!`file -exists -q $ExportFromFile`)
	{
		writeFile ( $ExportFromFile, $CurrentConnectionpFromText );
		print("成功导出" + $ExportFromFile + "\n");
	}
	else if (`file -exists -q $ExportFromFile`)
	{
		cleanFile ( $ExportFromFile );
		writeFile ( $ExportFromFile, $CurrentConnectionpFromText );
		print("成功覆盖" + $ExportFromFile + "\n");
	}
	if (!`file -exists -q $ExportToFile`)
	{
		writeFile ( $ExportToFile, $CurrentConnectionpToText );
		print("成功导出" + $ExportToFile + "\n");
	}
	else if (`file -exists -q $ExportToFile`)
	{
		cleanFile ( $ExportToFile );
		writeFile ( $ExportToFile, $CurrentConnectionpToText );
		print("成功覆盖" + $ExportToFile + "\n");
	}
}

//导入连接
global proc ImportConnection( string $SourceObject , string $ExportPath )
{
	string $ExportFromFile = $ExportPath + "/" + $SourceObject + ".from";
	string $ExportToFile = $ExportPath + "/" + $SourceObject + ".to";
	string $CurrentConnectionpFrom[];
	string $CurrentConnectionpTo[];
	if (`file -exists -q $ExportFromFile`)
	{
		int $fileId = `fopen $ExportFromFile "r"`;
		int $i = 0;
		while (!`feof $fileId`)
		{
			string $line = `fgetline $fileId`;
			if ($line != "") 
			{
				$CurrentConnectionpFrom[$i] = strip($line);
				$i++;
			}
		}
	}else
	{
		error ($ExportFromFile + "文件缺失！！\n");
	}
	if (`file -exists -q $ExportToFile`)
	{
		int $fileId = `fopen $ExportToFile "r"`;
		int $i = 0;
		while (!`feof $fileId`)
		{
			string $line = `fgetline $fileId`;
			if ($line != "") 
			{
				$CurrentConnectionpTo[$i] = strip($line);
				$i++;
			}
		}
	}else
	{
		error ($ExportToFile + "文件缺失！！\n");
	}
	//处理被连接
	for ($i=1; $i<size($CurrentConnectionpFrom); $i=$i+2)
	{
		connectAttr -f $CurrentConnectionpFrom[$i] $CurrentConnectionpFrom[$i-1];
	}
	//处理连接
	for ($i=0; $i<size($CurrentConnectionpTo); $i=$i+2)
	{
		connectAttr -f $CurrentConnectionpTo[$i] $CurrentConnectionpTo[$i+1];
	}
}

//断开连接
global proc BreakConnection( string $SourceObject , string $ExportPath )
{
	duplicate -n ($SourceObject + "_TMP") $SourceObject;
	string $ExportFromFile = $ExportPath + "/" + $SourceObject + ".from";
	string $ExportToFile = $ExportPath + "/" + $SourceObject + ".to";
	string $CurrentConnectionpFrom[];
	string $CurrentConnectionpTo[];
	if (`file -exists -q $ExportFromFile`)
	{
		int $fileId = `fopen $ExportFromFile "r"`;
		int $i = 0;
		while (!`feof $fileId`)
		{
			string $line = `fgetline $fileId`;
			if ($line != "") 
			{
				$CurrentConnectionpFrom[$i] = strip($line);
				$i++;
			}
		}
	}else
	{
		error ($ExportFromFile + "文件缺失！！\n");
	}
	if (`file -exists -q $ExportToFile`)
	{
		int $fileId = `fopen $ExportToFile "r"`;
		int $i = 0;
		while (!`feof $fileId`)
		{
			string $line = `fgetline $fileId`;
			if ($line != "") 
			{
				$CurrentConnectionpTo[$i] = strip($line);
				$i++;
			}
		}
	}else
	{
		error ($ExportToFile + "文件缺失！！\n");
	}
	//处理被连接
	for ($i=1; $i<size($CurrentConnectionpFrom); $i=$i+2)
	{
		if (`objExists $CurrentConnectionpFrom[$i]` && `objExists $CurrentConnectionpFrom[$i-1]`) 
		{
			if (`isConnected $CurrentConnectionpFrom[$i] $CurrentConnectionpFrom[$i-1]`)
			{
				disconnectAttr $CurrentConnectionpFrom[$i] $CurrentConnectionpFrom[$i-1];
				print ("移除连接 " + $CurrentConnectionpFrom[$i] + " 和 " + $CurrentConnectionpFrom[$i-1] + "\n");
			}
		}
	}
	//处理连接
	for ($i=0; $i<size($CurrentConnectionpTo); $i=$i+2)
	{
		if (`objExists $CurrentConnectionpTo[$i]` && `objExists $CurrentConnectionpTo[$i+1]`) 
		{
			if (`isConnected $CurrentConnectionpTo[$i] $CurrentConnectionpTo[$i+1]`)
			{
				disconnectAttr $CurrentConnectionpTo[$i] $CurrentConnectionpTo[$i+1];
				print ("移除连接 " + $CurrentConnectionpTo[$i] + " 和 " + $CurrentConnectionpTo[$i+1] + "\n");
			}
		}
	}
	delete $SourceObject;
	rename ($SourceObject + "_TMP") $SourceObject;
}

global proc BatchExportConnection()
{
	string $SourceAndTarget[] = `ls -sl`;
	for ($i = 0;$i < size($SourceAndTarget); $i++)
	{
		ExportConnection( $SourceAndTarget[$i] , "E:/Connections preset");
	}
}

global proc BatchImportConnection()
{
	string $SourceAndTarget[] = `ls -sl`;
	for ($i = 0;$i < size($SourceAndTarget); $i++)
	{
		ImportConnection( $SourceAndTarget[$i] , "E:/Connections preset");
	}
}

global proc BatchBreakConnection()
{
	string $SourceAndTarget[] = `ls -sl`;
	for ($i = 0;$i < size($SourceAndTarget); $i++)
	{
		BreakConnection( $SourceAndTarget[$i] , "E:/Connections preset");
	}
}

BatchExportConnection();
BatchImportConnection();
BatchBreakConnection();