//加载公共函数
eval ("source \"" + `asInstallScriptLocation` + "Scripts/ALLPublicScripts.mel\"");

////////////////////////////////////////////////////////////////
// 全局函数
////////////////////////////////////////////////////////////////
global string $BackStartPath;
global string $ReturnStartflag;
global string $ReturntextFieldName;

////////////////////////////////////////////////////////////////
// UI函数
////////////////////////////////////////////////////////////////
//窗口
global proc showFileBrowser ( string $ReturntextFieldInputflag, string $StartPath, string $ReturntextFieldInputName )
{
	global string $MFBSettingInformation[];
	$MFBSettingInformation[0] = "1";
	global string $BackStartPath;
	$BackStartPath = $StartPath;
	global string $ReturnStartflag;
	$ReturnStartflag = $ReturntextFieldInputflag;
	global string $ReturntextFieldName;
	$ReturntextFieldName = $ReturntextFieldInputName;
	if (`window -exists "MayaFileBrowserWindow"`)
	{
		deleteUI -window "MayaFileBrowserWindow";
	}
	window -title "文件资源管理器" -widthHeight 848 418 -sizeable 0 -minimizeButton true-maximizeButton true MayaFileBrowserWindow;
		columnLayout -columnAttach both 5 -adjustableColumn true MayaFileBrowsercolumnLayout;
			separator -height 5 -style "none";
			// 创建顶部工具栏
			createToolbar();
			separator -height 5 -style "none";
			separator -height 2;
			// 创建路径显示区域
			createPathInput();
			textField -e -tx $StartPath MFBPathTextField;
			separator -height 2;
			rowColumnLayout -numberOfColumns 3 
				-height 320
				-adjustableColumn 2 
				-columnWidth 1 140 //插件预设和收藏目录
				-columnWidth 2 490 //显示目录和分类显示
				-columnWidth 3 204 //备注内容
				MFBMainDisplay;
				// 创建主内容区域
				createLeftDisplay();
				createPathDisplay();
				createRightDisplay();
			setParent ..;
			// 创建底部状态栏
			separator -height 2;
			createStatusBar();
			separator -height 5 -style "none";
	showWindow MayaFileBrowserWindow;
	//初始化值
	global string $KeepRememberPathString[];
	$KeepRememberPathString = {};
	textField -e -text $StartPath MFBPathTextField;
	MFBnavigateToPath(1);
	if ($ReturntextFieldName == 0)
	{
		button -e -en 0 MFBConfirmdisplaypath;
	}
}

//顶栏
global proc createToolbar ()
{
	rowColumnLayout -numberOfColumns 15 
		-height 24
		-columnWidth 1 65 
		-columnWidth 2 65 
		-columnWidth 3 20 
		-columnWidth 4 65 
		-columnWidth 5 65 
		-columnWidth 6 65 
		-columnWidth 7 65 
		-columnWidth 8 65 
		-columnWidth 9 65 
		-columnWidth 10 20 
		-columnWidth 11 65 
		-columnWidth 12 65 
		-columnWidth 13 65 
		-columnWidth 14 65 
		-columnWidth 15 14 
		MFBtoolbar;
		string $SettingPathimage = `asInstallScriptLocation` + "Icon/SettingPathSmall.svg";
		iconTextButton -command "占位符" -ann "进行插件设置" -style "iconAndTextHorizontal" -image1 $SettingPathimage -label "设　置";
		string $Diskimageimage = `asInstallScriptLocation` + "Icon/DiskSmall.svg";
		iconTextButton -command "MFBSystemDrives" -ann "显示磁盘路径" -style "iconAndTextHorizontal" -image1 $Diskimageimage -label "磁　盘";
		string $Delimiterimage = `asInstallScriptLocation` + "Icon/DelimiterSmall.svg";
		image -image $Delimiterimage;
		string $EditSmallimage = `asInstallScriptLocation` + "Icon/EditSmall.svg";
		iconTextButton -command "MFBrenameSelected(0)" -ann "重命名当前目录" -style "iconAndTextHorizontal" -image1 $EditSmallimage -label "重命名";
		string $CopySmallimage = `asInstallScriptLocation` + "Icon/CopySmall.svg";
		iconTextButton -command "MFBcopySelected(0)" -ann "复制当前目录" -style "iconAndTextHorizontal" -image1 $CopySmallimage -label "复　制";
		string $CutSmallimage = `asInstallScriptLocation` + "Icon/CutSmall.svg";
		iconTextButton -command "MFBcutSelected(0)" -ann "剪切当前目录" -style "iconAndTextHorizontal" -image1 $CutSmallimage -label "剪　切";
		string $PasteSmallimage = `asInstallScriptLocation` + "Icon/PasteSmall.svg";
		iconTextButton -command "MFBpasteSelected(0)" -ann "粘贴复制目录" -style "iconAndTextHorizontal" -image1 $PasteSmallimage -label "粘　贴";
		string $AddFileSmallimage = `asInstallScriptLocation` + "Icon/AddFileSmall.svg";
		iconTextButton -command "MFBcreateNewFolder" -ann "新建文件夹" -style "iconAndTextHorizontal" -image1 $AddFileSmallimage -label "新　建";
		string $DeleteSmallimage = `asInstallScriptLocation` + "Icon/DeleteSmall.svg";
		iconTextButton -command "MFBdeleteSelected(0)" -ann "删除当前目录" -style "iconAndTextHorizontal" -image1 $DeleteSmallimage -label "删　除";
		image -image $Delimiterimage;
		string $OpenFileSmallimage = `asInstallScriptLocation` + "Icon/OpenFileSmall.svg";
		iconTextButton -command "MFBopenFolder(0)" -ann "在资源管理器中打开" -style "iconAndTextHorizontal" -image1 $OpenFileSmallimage -label "打　开";
		string $LockSmallimage = `asInstallScriptLocation` + "Icon/LockSmall.svg";
		iconTextButton -command "MFBLockReadOnly(0)" -ann "设置文件属性为只读" -style "iconAndTextHorizontal" -image1 $LockSmallimage -label "锁　定";//把文件属性改为只读
		string $UnlockSmallimage = `asInstallScriptLocation` + "Icon/UnlockSmall.svg";
		iconTextButton -command "MFBUnlockReadOnly(0)" -ann "解除文件属性为只读" -style "iconAndTextHorizontal" -image1 $UnlockSmallimage -label "解　锁";//取消文件属性只读
		string $RefreshSmallimage = `asInstallScriptLocation` + "Icon/RefreshSmall.svg";
		iconTextButton -command "MFBReflushshowitems" -ann "刷新文件列表" -style "iconAndTextHorizontal" -image1 $RefreshSmallimage -label "刷　新";
		//可调整窗口
		string $SLetterimage = `asInstallScriptLocation` + "Icon/SLetterSmall.svg";
		symbolButton -command "if(`window -q -sizeable MayaFileBrowserWindow`==0){window -e -sizeable 1 MayaFileBrowserWindow;print (\"窗口可调节！\\n\");}else{window -e -sizeable 0 MayaFileBrowserWindow;print (\"窗口锁定！\\n\");}" -ann "改变窗口锁定" -height 14 -image $SLetterimage;
	setParent ..;
}

//路径栏
global proc createPathInput ()
{
	rowColumnLayout -numberOfColumns 9
		-adjustableColumn 2 
		-height 25
		-columnWidth 1 140 
		-columnWidth 2 490 
		-columnWidth 3 25 
		-columnWidth 4 25 
		-columnWidth 5 25 
		-columnWidth 6 25 
		-columnWidth 7 25 
		-columnWidth 8 25 
		-columnWidth 9 54 
		MFBPathDisplay;
		text -label "　 输 入 浏 览 路 径 ：";
		textField -editable true 
			-hlc 0.5 0.5 0.5 
			-text ""
			-enterCommand "MFBnavigateToPath(1)"
			MFBPathTextField;
		//复制显示的路径
		string $CLetterimage = `asInstallScriptLocation` + "Icon/CLetter.svg";
		symbolButton -h 20 -ann "复制路径" -image $CLetterimage -c "MFBCopyPath(0)";
		//收藏显示的路径
		string $Favoriteimage = `asInstallScriptLocation` + "Icon/Favorite.svg";
		symbolButton -h 20 -ann "收藏路径" -image $Favoriteimage -c "MFBFavoritePath(0)";
		//上一次输入的路径
		string $LeftArrowimage = `asInstallScriptLocation` + "Icon/LeftArrow.svg";
		symbolButton -h 20 -ann "返回路径" -image $LeftArrowimage -c "MFBBeforePath";
		//下一次输入的路径
		string $AfterPathimage = `asInstallScriptLocation` + "Icon/RightArrow.svg";
		symbolButton -h 20 -ann "恢复路径" -image $AfterPathimage -c "MFBAfterPath";
		//上级路径
		string $UpArrowimage = `asInstallScriptLocation` + "Icon/UpArrow.svg";
		symbolButton -h 20 -ann "上级路径" -image $UpArrowimage -c "MFBUpPath";
		//启动时路径
		string $Returnimage = `asInstallScriptLocation` + "Icon/Return.svg";
		symbolButton -h 20 -ann "启动路径" -image $Returnimage -c "MFBStartPath";
		button -label "前 往" 
			   -command "MFBnavigateToPath(1)";
	setParent ..;
}

//插件预设（缓存）和收藏目录栏
global proc createLeftDisplay ()
{
	columnLayout -adjustableColumn true MFBLeftcolumnLayout;
		paneLayout -configuration "horizontal2" -height 315 MFBLeftpaneLayout;
			frameLayout -height 80 -cl 0 -cll 0 -label "预设目录" MFBPreframeLayout;
				textScrollList -hlc 0.5 0.5 0.5 -sc "MFBGOPrePath" -allowMultiSelection 0 MFBPretextScrollList;
				MFBLoadPrePath();
			setParent ..;
			frameLayout -height 80 -cl 0 -cll 0 -label "收藏目录" MFBFavoritesframeLayout;
				textScrollList -hlc 0.5 0.5 0.5 -sc "MFBGOFavoritesPath" -allowMultiSelection 0 MFBFavoritestextScrollList;
				MFBLoadFavoritesPath();
			setParent ..;
		setParent ..;
	setParent ..;
}

//显示目录栏和分类栏
global proc createPathDisplay ()
{
	rowColumnLayout -numberOfColumns 3 
		-height 320 
		-adjustableColumn 1 
		-columnWidth 1 400 
		-columnWidth 2 87 
		MFBPathDisplayrowcolumnLayout;
		paneLayout -paneSize 2 1 4 -configuration "vertical2" -width 400 MFBPathDisplaypaneLayout;
			columnLayout -width 80  -adjustableColumn true MFBFileInformationDisplaycolumnLayout1;
				optionMenu -changeCommand "ChangeOptionMenuCommand1" -height 20 MFBFileInformationDisplayoptionMenu1;
					MFBFileInformationDisplaymenuItem();
					optionMenu -edit -select 1 MFBFileInformationDisplayoptionMenu1;
				textScrollList -height 293 -hlc 0.5 0.5 0.5 -sc "MFBtextScrollListSynchronize(1)" -dcc "MFBtextScrollListOpen" -allowMultiSelection 0 MFBPathDisplaytextScrollList;
			setParent ..;
			columnLayout -width 80  -adjustableColumn true MFBFileInformationDisplaycolumnLayout2;
				optionMenu -changeCommand "ChangeOptionMenuCommand2" -height 20 MFBFileInformationDisplayoptionMenu2;
					MFBFileInformationDisplaymenuItem();
					optionMenu -edit -select 2 MFBFileInformationDisplayoptionMenu2;
				textScrollList -height 293 -hlc 0.5 0.5 0.5 -sc "MFBtextScrollListSynchronize(2)" -dcc "MFBtextScrollListOpen" -allowMultiSelection 0 MFBFileDatetextScrollList;
			setParent ..;
		setParent ..;
		columnLayout -width 87 -adjustableColumn true MFBCategorycolumnLayout;
			frameLayout -cl 0 -cll 0 -label "  　分　类" MFBCategoryframeLayout;
				scrollLayout -height 293 -width 85 -bv 1 MFBPathDisplayscrollLayout;
				//scrollLayout -q -numberOfChildren MFBPathDisplayscrollLayout;查询子对象数量
					button -label "文件夹(0)" 
						-command "showFileInBrowser(0)"
						-ann "显示文件夹"
						-ebg 1
						-width 76
						-height 20
						-backgroundColor 0.3 0.6 0.3//0.265 0.265 0.265 
						FileCategory0;
				setParent ..;
			setParent ..;
		setParent ..;
	setParent ..;
}

global proc MFBFileInformationDisplaymenuItem ()
{
	menuItem -label "文件名称" MFBFileInformationDisplaymenuItem0;
	menuItem -label "创建时间" MFBFileInformationDisplaymenuItem1;
	menuItem -label "修改时间" MFBFileInformationDisplaymenuItem2;
	menuItem -label "访问时间" MFBFileInformationDisplaymenuItem3;
}

//备注栏
global proc createRightDisplay ()
{
	columnLayout -height 350 -adjustableColumn true MFBRightcolumnLayout;
		frameLayout -cl 0 -cll 0 -label "　　　　　　 备　 注" MFBFavoritesframeLayout;
			scrollField -height 260 -editable false -wordWrap true -text "" MFBRemarksTextField;
			rowColumnLayout -numberOfColumns 2 -columnWidth 1 102 -columnWidth 2 102 MFBRemarksrowColumnLayout;
				button -label "编辑" 
					-command "navigateUp"
					-ann "编辑备注";
				button -label "保存" 
					-command "navigateUp"
					-ann "编辑保存";
			setParent ..;
		setParent ..;
	setParent ..;
}

//底栏
global proc createStatusBar ()
{
	rowColumnLayout -numberOfColumns 6 -adjustableColumn 3 -columnWidth 1 65 -columnWidth 2 55 -columnWidth 3 411 -columnWidth 4 100 -columnWidth 5 102 -columnWidth 6 101;
		text -label "就绪" -align "left" MFBShowFileTotal;
		text -label "" -align "left" MFBStatusLabel;
		text -label "" -align "left" MFBShowPathtext;
		text -label "" MFBFileSizetext;
		button -label "确定显示路径" -command "returnFileBrowser" MFBConfirmdisplaypath;
		button -label "操作选中文件" -command "占位符";
	setParent ..;
}

////////////////////////////////////////////////////////////////
// 工具函数
////////////////////////////////////////////////////////////////
//全局函数
global int $BackCount;
global string $RememberPathString[];
global string $KeepRememberPathString[];
global string $MFBSettingInformation[];
global string $textScrollListFileNames[];
global string $textScrollListCreationTimes[];
global string $textScrollListModificationTimes[];
global string $textScrollListAccessTimes[];
global int $CategoryNums[];
global string $KeeptextScrollListFileNames[];
global string $KeeptextScrollListCreationTimes[];
global string $KeeptextScrollListModificationTimes[];
global string $KeeptextScrollListAccessTimes[];

//加载预设目录
global proc MFBLoadPrePath ()
{
	textScrollList -e -removeAll MFBPretextScrollList;
	//加载预设配置
	string $SettingfilePath = `asInstallScriptLocation` + "PublicFiles/Settings/Setting.set";
	string $EachSettingline[] = freadAllLines($SettingfilePath);
	for ($i=0; $i<size($EachSettingline); $i++)
	{
		string $Information[];
		tokenize($EachSettingline[$i],"：",$Information);
		textScrollList -e -append $Information[0] MFBPretextScrollList;
	}
}

//加载收藏目录
global proc MFBLoadFavoritesPath ()
{
	textScrollList -e -removeAll MFBFavoritestextScrollList;
	//加载收藏配置
	string $FavoritesfilePath = `asInstallScriptLocation` + "PublicFiles/Settings/FavoritesPath.set";
	$EachSettingline = freadAllLines($FavoritesfilePath);
	for ($i=0; $i<size($EachSettingline); $i++)
	{
		string $Information[];
		tokenize($EachSettingline[$i],"：",$Information);
		textScrollList -e -append $Information[0] MFBFavoritestextScrollList;
	}
}

//显示磁盘路径
global proc MFBSystemDrives ()
{
	global string $KeeptextScrollListFileNames[];
	global string $KeeptextScrollListCreationTimes[];
	global string $KeeptextScrollListModificationTimes[];
	global string $KeeptextScrollListAccessTimes[];
	$KeeptextScrollListFileNames = {};
	$KeeptextScrollListCreationTimes = {};
	$KeeptextScrollListModificationTimes = {};
	$KeeptextScrollListAccessTimes = {};
	string $DriveNames[] = getSystemDrives();
	textScrollList -e -removeAll MFBPathDisplaytextScrollList;
	textScrollList -e -removeAll MFBFileDatetextScrollList;
	for ($i=0; $i<size($DriveNames); $i++)
	{
		textScrollList -e -append $DriveNames[$i] MFBPathDisplaytextScrollList;
		textScrollList -e -append $DriveNames[$i] MFBFileDatetextScrollList;
	}
	optionMenu -e -enable 0 MFBFileInformationDisplayoptionMenu1;
	optionMenu -e -enable 0 MFBFileInformationDisplayoptionMenu2;
	button -e -enable 0 -backgroundColor 0.265 0.265 0.265  -label "文件夹(0)" FileCategory0;
	textField -e -text "SystemDisks" MFBPathTextField;
	text -e -label (size($DriveNames) + "个磁盘" + "　|　") MFBShowFileTotal;
	text -e -label "电脑磁盘" MFBShowPathtext;
	MFBaddCategory();
}

//预设目录
global proc MFBGOPrePath ()
{
	string $SettingfilePath = `asInstallScriptLocation` + "PublicFiles/Settings/Setting.set";
	string $EachSettingline[] = freadAllLines($SettingfilePath);
	int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBPretextScrollList`;
	string $Information[];
	tokenize($EachSettingline[$SelectIndexed[0]-1],"：",$Information);
	textField -e -text $Information[1] MFBPathTextField;
	MFBnavigateToPath(1);
}

//收藏目录
global proc MFBGOFavoritesPath ()
{
	string $FavoritesfilePath = `asInstallScriptLocation` + "PublicFiles/Settings/FavoritesPath.set";
	string $EachSettingline[] = freadAllLines($FavoritesfilePath);
	int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBFavoritestextScrollList`;
	string $Information[];
	tokenize($EachSettingline[$SelectIndexed[0]-1],"：",$Information);
	textField -e -text $Information[1] MFBPathTextField;
	MFBnavigateToPath(1);
	warning ("已经前往收藏目录！！！");
}

//返回信息
global proc returnFileBrowser ()
{
	global string $ReturnStartflag;
	global string $ReturntextFieldName;
	string $Path =$ReturnStartflag + "\"" + `text -q -label MFBShowPathtext` + "\"" + "-e " + $ReturntextFieldName;
	eval $Path;
	if (`window -exists "MayaFileBrowserWindow"`)
	{
		deleteUI -window "MayaFileBrowserWindow";
	}
}

//复制选中文件
global proc MFBcopySelected ( int $List )
{
}

//剪切选中文件
global proc MFBcutSelected ( int $List )
{
}

//粘贴选中文件
global proc MFBpasteSelected ( int $List )
{
}

//重命名选中文件
global proc MFBrenameSelected ( int $List )
{
}

//创建新文件夹
global proc MFBcreateNewFolder ()
{
}

//删除选中文件
global proc MFBdeleteSelected ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $Path = `text -q -label MFBShowPathtext`;
		if (`filetest -d $Path`)
        {
            // 删除文件夹及其所有内容
			$Path = toNativePath($Path);
            string $command = "rmdir /s /q \"" + $Path + "\"";
			system($command);
        }
        else
        {
            // 删除文件
			$Path = toNativePath($Path);
            string $command = "del /f /q \"" + $Path + "\"";
			system($command);
        }
	}
}

//设置为只读
global proc MFBLockReadOnly ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $Path = `text -q -label MFBShowPathtext`;
		setFileReadOnly( $Path );
	}
}

//解除只读
global proc MFBUnlockReadOnly ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $Path = `text -q -label MFBShowPathtext`;
		removeFileReadOnly( $Path );
	}
}

//在文件资源管理器中打开文件夹
global proc MFBopenFolder ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $Path = toNativePath(`text -q -label MFBShowPathtext`);
		if ($Path == "电脑磁盘")
		{
			string $command = "explorer shell:MyComputerFolder";
			system($command);
		}else
		{
			string $command = "explorer \"" + $Path + "\"";
			system($command);
		}
	}
}

//复制路径
global proc MFBCopyPath ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $Path = `text -q -label MFBShowPathtext`;
		$Path = toNativePath($Path);
		copyToClipboard($Path, 1);
	}
}

//收藏路径
global proc MFBFavoritePath ( int $List )
{
	if ($List == 1)
	{
		// Statements;
	}else
	{
		string $FavoritefilePath = `asInstallScriptLocation` + "PublicFiles/Settings/FavoritesPath.set";
		string $EachSettingline[] = freadAllLines($FavoritefilePath);
		string $Path = `text -q -label MFBShowPathtext`;
		if (`filetest -e $Path`)
		{
			int $FavoriteKey = 0;
			for ($Settingline in $EachSettingline)
			{
				if (`gmatch $Settingline ("*" + $Path)`)
				{
					$FavoriteKey = 1;
				}
			}
			if ($FavoriteKey == 1)
			{
				warning ("已存在收藏：\n" + $Settingline);
			}else
			{
				string $content;
				if (`gmatch $Path "*://"`)
				{
					$content = "磁盘" + `substring $Path 1 (size($Path)-3)` + "：" + $Path + "\n";
				}else
				{
					$content = basename( $Path, "" ) + "：" + $Path + "\n";
				}
				writeFile ( $FavoritefilePath, $content );
				MFBLoadFavoritesPath();
				warning ("收藏成功！！！");
			}
		}else
		{
			warning ("非法路径！！！");
		}
	}
}

//返回路径
global proc MFBBeforePath ()
{
	global int $BackCount;
	global string $RememberPathString[];
	global string $KeepRememberPathString[];
	if ($BackCount == 0)
	{
		$RememberPathString = $KeepRememberPathString;
	}
	if ((size($RememberPathString)-1) == 0)
	{
		warning ("无返回路径！！！");
	}else
	{
		stringArrayRemoveAtIndex((size($RememberPathString)-1), $RememberPathString);
		$BackCount = ($BackCount + 1);
		textField -e -text $RememberPathString[size($RememberPathString)-1] MFBPathTextField;
		MFBnavigateToPath(0);
	}
}

//恢复路径
global proc MFBAfterPath ()
{
	global int $BackCount;
	global string $RememberPathString[];
	global string $KeepRememberPathString[];
	if ($BackCount == 0)
	{
		warning ("无恢复路径！！！");
	}else
	{
		$BackCount = ($BackCount - 1);
		$RememberPathString[size($RememberPathString)] = $KeepRememberPathString[size($RememberPathString)];
		textField -e -text $RememberPathString[size($RememberPathString)-1] MFBPathTextField;
		MFBnavigateToPath(0);
	}
}

//上级路径
global proc MFBUpPath ()
{
	string $UpPath = dirname(`textField -q -text MFBPathTextField`);
	textField -e -text $UpPath MFBPathTextField;
	MFBnavigateToPath(1);
}

//启动路径
global proc MFBStartPath ()
{
	global string $BackStartPath;
	if($BackStartPath == "")
	{
		warning ("无启动路径");
	}else
	{
		textField -e -text $BackStartPath MFBPathTextField;
		MFBnavigateToPath(1);
	}
}

//跟随选择并获取文件大小
global proc MFBtextScrollListSynchronize ( int $List )
{
	if ($List == 1)
	{
		int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBPathDisplaytextScrollList`;
		textScrollList -e -selectIndexedItem $SelectIndexed[0] MFBFileDatetextScrollList;
	}
	if ($List == 2)
	{
		int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBFileDatetextScrollList`;
		textScrollList -e -selectIndexedItem $SelectIndexed[0] MFBPathDisplaytextScrollList;
	}
	string $Path = `text -q -label MFBShowPathtext`;
	global string $KeeptextScrollListFileNames[];
	global string $MFBSettingInformation[];
	if ($MFBSettingInformation[0] == "1")
	{
		if (`gmatch $Path "电脑磁盘"`)
		{
			string $SelectItem[] = `textScrollList -q -selectItem MFBPathDisplaytextScrollList`;
			string $Content = getFileSizeFormatted($SelectItem[0]);
			text -e -label $Content MFBFileSizetext;
		}else
		{
			if (`gmatch $Path "*://"`)
			{
				$Path = `substring $Path 1 (size($Path)-1)`;
			}
			if (!`gmatch $Path "*/"`)
			{
				$Path = $Path + "/";
			}
			int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBPathDisplaytextScrollList`;
			$Path = $Path + $KeeptextScrollListFileNames[$SelectIndexed[0]-1];
			string $Content = getFileSizeFormatted($Path);
			text -e -label $Content MFBFileSizetext;
		}
	}else
	{
		text -e -label "未启用大小读取" MFBFileSizetext;
	}
}

//进入文件夹
global proc MFBtextScrollListOpen ()
{
	string $InputPath = `text -q -label MFBShowPathtext`;
	if (`gmatch $InputPath "*://"`)
	{
		$InputPath = `substring $InputPath 1 (size($InputPath)-1)`;
	}
	if (!`gmatch $InputPath "*/"`)
	{
		$InputPath = $InputPath + "/";
	}
	global string $KeeptextScrollListFileNames[];
	global string $textScrollListFileNames[];
	global int $CategoryNums[];
	string $Folders[] = {};
	for ($i=0; $i<$CategoryNums[0]; $i++)
	{
		$Folders[$i] = $textScrollListFileNames[$i];
	}
	int $SelectIndexed[] = `textScrollList -q -selectIndexedItem MFBPathDisplaytextScrollList`;
	int $IsFolders = stringArrayContains($KeeptextScrollListFileNames[$SelectIndexed[0]-1], $Folders);
	if ($IsFolders == 0)
	{
		string $SelectContent[] = `textScrollList -q -selectItem MFBPathDisplaytextScrollList`;
		if (`gmatch $SelectContent[0] "*://"`)
		{
			textField -e -text $SelectContent[0] MFBPathTextField;
			MFBnavigateToPath(1);
		}else
		{
			warning ("非文件夹！！！");
		}
	}else
	{
		$InputPath = $InputPath + $KeeptextScrollListFileNames[$SelectIndexed[0]-1];
		textField -e -text $InputPath MFBPathTextField;
		MFBnavigateToPath(1);
	}
}

//刷新显示内容
global proc MFBReflushshowitems ()
{
	string $InputPath = `text -q -label MFBShowPathtext`;
	if ($InputPath == "电脑磁盘")
	{
		MFBSystemDrives();
	}else
	{
		textField -e -text $InputPath MFBPathTextField;
		MFBnavigateToPath(0);
	}
}

//改变显示类型1
global proc ChangeOptionMenuCommand1 ()
{
	global string $KeeptextScrollListFileNames[];
	global string $KeeptextScrollListCreationTimes[];
	global string $KeeptextScrollListModificationTimes[];
	global string $KeeptextScrollListAccessTimes[];
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu1` == 1)
	{
		MFBFileDisplaytextScrollList1($KeeptextScrollListFileNames);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu1` == 2)
	{
		MFBFileDisplaytextScrollList1($KeeptextScrollListCreationTimes);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu1` == 3)
	{
		MFBFileDisplaytextScrollList1($KeeptextScrollListModificationTimes);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu1` == 4)
	{
		MFBFileDisplaytextScrollList1($KeeptextScrollListAccessTimes);
	}
}

//改变显示类型2
global proc ChangeOptionMenuCommand2 ()
{
	global string $KeeptextScrollListFileNames[];
	global string $KeeptextScrollListCreationTimes[];
	global string $KeeptextScrollListModificationTimes[];
	global string $KeeptextScrollListAccessTimes[];
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu2` == 1)
	{
		MFBFileDisplaytextScrollList2($KeeptextScrollListFileNames);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu2` == 2)
	{
		MFBFileDisplaytextScrollList2($KeeptextScrollListCreationTimes);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu2` == 3)
	{
		MFBFileDisplaytextScrollList2($KeeptextScrollListModificationTimes);
	}
	if (`optionMenu -q -select MFBFileInformationDisplayoptionMenu2` == 4)
	{
		MFBFileDisplaytextScrollList2($KeeptextScrollListAccessTimes);
	}
}

//显示文件类型
global proc showFileInBrowser ( string $Category )
{
	//改变按钮状态
	if (`button -q -ebg ("FileCategory" + $Category)` == 1)
	{
		button -e -ebg 0 -backgroundColor 0.265 0.265 0.265 ("FileCategory" + $Category);
	}else
	{
		button -e -ebg 1 -backgroundColor 0.3 0.6 0.3 ("FileCategory" + $Category);
	}
	//剔除不显示内容
	global string $textScrollListFileNames[];
	global string $textScrollListCreationTimes[];
	global string $textScrollListModificationTimes[];
	global string $textScrollListAccessTimes[];
	global int $CategoryNums[];
	global string $KeeptextScrollListFileNames[];
	global string $KeeptextScrollListCreationTimes[];
	global string $KeeptextScrollListModificationTimes[];
	global string $KeeptextScrollListAccessTimes[];
	$KeeptextScrollListFileNames = {};
	$KeeptextScrollListCreationTimes = {};
	$KeeptextScrollListModificationTimes = {};
	$KeeptextScrollListAccessTimes = {};
	int $NewNum = 0;
	int $BaseNum = 0;
	string $CategoryName[] = `scrollLayout -q -ca MFBPathDisplayscrollLayout`;
	for ($i=0; $i<size($CategoryName); $i++)
	{
		if ($i != 0)
		{
			$BaseNum = $BaseNum + $CategoryNums[$i-1];
		}
		if (`button -q -ebg ("FileCategory" + $i)` == 1)
		{
				for ($a=0; $a<$CategoryNums[$i]; $a++)
				{
					$KeeptextScrollListFileNames[$NewNum] = $textScrollListFileNames[$BaseNum + $a];
					$KeeptextScrollListCreationTimes[$NewNum] = $textScrollListCreationTimes[$BaseNum + $a];
					$KeeptextScrollListModificationTimes[$NewNum] = $textScrollListModificationTimes[$BaseNum + $a];
					$KeeptextScrollListAccessTimes[$NewNum] = $textScrollListAccessTimes[$BaseNum + $a];
					$NewNum = $NewNum + 1;
				}
		}
	}
	ChangeOptionMenuCommand1();
	ChangeOptionMenuCommand2();
}

//转到路径
global proc MFBnavigateToPath ( int $RememberPath )
{
	string $InputPath = `textField -q -text MFBPathTextField`;
	//处理输入路径
	$InputPath = fromNativePath($InputPath);
	$InputPath = fromNativePath($InputPath);
	if (`gmatch $InputPath "*:/"`)
	{
		$InputPath = $InputPath + "/";
	}
	if (`gmatch $InputPath "*/"` && !`gmatch $InputPath "*://"`)
	{
		$InputPath = `substring $InputPath 1 (size($InputPath)-1)`;
	}
	if ($InputPath == "")
	{
		warning ("请输入路径！！");
	}else if (!`filetest -e $InputPath`)
	{
		warning ("路径不存在！！");
	}else 
	{
		string $AllFileName[] = `getFileList -folder $InputPath`;
		button -e -backgroundColor 0.3 0.6 0.3 FileCategory0;
		textField -e -text $InputPath MFBPathTextField;
		text -e -label "显示路径：" MFBStatusLabel;
		text -e -label $InputPath MFBShowPathtext;
		text -e -label (size($AllFileName) + "个项目" + "　|　") MFBShowFileTotal;
		MFBaddCategory();
		MFBFileDisplayContent($InputPath);
		global string $textScrollListFileNames[];
		global string $textScrollListCreationTimes[];
		global string $textScrollListModificationTimes[];
		global string $textScrollListAccessTimes[];
		global string $KeeptextScrollListFileNames[];
		global string $KeeptextScrollListCreationTimes[];
		global string $KeeptextScrollListModificationTimes[];
		global string $KeeptextScrollListAccessTimes[];
		$KeeptextScrollListFileNames = $textScrollListFileNames;
		$KeeptextScrollListCreationTimes = $textScrollListCreationTimes;
		$KeeptextScrollListModificationTimes = $textScrollListModificationTimes;
		$KeeptextScrollListAccessTimes = $textScrollListAccessTimes;
		ChangeOptionMenuCommand1();
		ChangeOptionMenuCommand2();
	}
	global int $BackCount;
	global string $RememberPathString[];
	global string $KeepRememberPathString[];
	if ($RememberPath == 1)
	{
		//初始化路径存储信息
		$BackCount = 0;
		$RememberPathString = {};
		//累加存储路径
		$KeepRememberPathString[size($KeepRememberPathString)] = $InputPath;
	}
	if (`optionMenu -q -enable MFBFileInformationDisplayoptionMenu1` == 0)
	{
		optionMenu -e -enable 1 MFBFileInformationDisplayoptionMenu1;
	}
	if (`optionMenu -q -enable MFBFileInformationDisplayoptionMenu2` == 0)
	{
		optionMenu -e -enable 1 MFBFileInformationDisplayoptionMenu2;
	}
	if (`button -q -enable FileCategory0` == 0)
	{
		button -e -enable 1 FileCategory0;
	}
}

//新增分类
global proc MFBaddCategory ()
{
	string $InputPath = `text -q -label MFBShowPathtext`;
	string $CategoryName[] = `scrollLayout -q -ca MFBPathDisplayscrollLayout`;
	string $getFoldersName[] = getFoldersInDirectory($InputPath);
	string $getCategoryName[] = getFileTypesWithCount($InputPath);
	button -e -label ("文件夹(" + size($getFoldersName) + ")") FileCategory0;
	if (size($CategoryName)>1)
	{
		for ($i=1; $i<size($CategoryName); $i++)
		{
			deleteUI ("FileCategory" + $i);
		}
	}
	for ($i=1; $i<size($getCategoryName); $i++)
	{
		string $getCategoryOnlyName[] = stringToStringArray($getCategoryName[$i], ".:");
		button -label ($getCategoryOnlyName[0] + "(" + $getCategoryOnlyName[1] + ")")
			-command ("showFileInBrowser(" + $i + ")")
			-ann ("仅显示" + $getCategoryOnlyName[0] + "文件")
			-ebg 1
			-width 76
			-height 20
			-backgroundColor 0.3 0.6 0.3 
			-parent MFBPathDisplayscrollLayout 
			("FileCategory" + $i);
	}
}

//获取信息显示框显示内容
global proc MFBFileDisplayContent ( string $InputPath )
{
	global string $textScrollListFileNames[];
	global string $textScrollListCreationTimes[];
	global string $textScrollListModificationTimes[];
	global string $textScrollListAccessTimes[];
	global int $CategoryNums[];
	$textScrollListFileNames = {};
	$textScrollListCreationTimes = {};
	$textScrollListModificationTimes = {};
	$textScrollListAccessTimes = {};
	$CategoryNums = {};
	//选择显示文件名称
		//获取文件夹名
			string $FoldersName[] = getFoldersInDirectory($InputPath);
			$CategoryNums[0] = size($FoldersName);
			if (size($FoldersName) != 0 )
			{
				$textScrollListFileNames = $FoldersName;
			}
		//获取各类文件名
			string $CategoryName[] = `scrollLayout -q -ca MFBPathDisplayscrollLayout`;
			for ($i=1; $i<size($CategoryName); $i++)
			{
				string $getCategoryOnlyName[] = stringToStringArray(`button -q -label ("FileCategory" + $i)`, "(");
				if ($getCategoryOnlyName[0] == "未知")
				{
					string $Unknown[] = `getFileList -folder $InputPath -filespec "*."`;
					$Unknown = getStringArrayDifference($Unknown, getFoldersInDirectory($InputPath));
					$CategoryNums[$i] = size($Unknown);
					$textScrollListFileNames = mergeStringArrays($textScrollListFileNames, $Unknown);
				}else
				{
					string $AddContent[] = `getFileList -folder $InputPath -filespec ("*." + $getCategoryOnlyName[0])`;
					$CategoryNums[$i] = size($AddContent);
					$textScrollListFileNames = mergeStringArrays($textScrollListFileNames, $AddContent);
				}
			}
	//选择显示创建时间
		//获取文件夹创建时间
			if (size($FoldersName) != 0 )
			{
				for ($i=0; $i<size($FoldersName); $i++) 
				{
					string $FoldersNameTmp[] = getFileTimes(($InputPath + "/" + $FoldersName[$i]));
					$textScrollListCreationTimes[$i] = $FoldersNameTmp[0];
				}
			}
		//获取各类文件创建时间
			for ($i=1; $i<size($CategoryName); $i++)
			{
				string $getCategoryOnlyName[] = stringToStringArray(`button -q -label ("FileCategory" + $i)`, "(");
				if ($getCategoryOnlyName[0] == "未知")
				{
					string $Unknown[] = `getFileList -folder $InputPath -filespec "*."`;
					$Unknown = getStringArrayDifference($Unknown, getFoldersInDirectory($InputPath));
					for ($a=0; $a<size($Unknown); $a++) 
					{
						string $textScrollListCreationTimesTmp[] = getFileTimes(($InputPath + "/" + $Unknown[$a]));
						$Unknown[$a] = $textScrollListCreationTimesTmp[0];
					}
					$textScrollListCreationTimes = mergeStringArrays($textScrollListCreationTimes, $Unknown);
				}else
				{
					string $AddContent[] = `getFileList -folder $InputPath -filespec ("*." + $getCategoryOnlyName[0])`;
					for ($b=0; $b<size($AddContent); $b++) 
					{
						string $textScrollListCreationTimesTmp[] = getFileTimes(($InputPath + "/" + $AddContent[$b]));
						$AddContent[$b] = $textScrollListCreationTimesTmp[0];
					}
					$textScrollListCreationTimes = mergeStringArrays($textScrollListCreationTimes, $AddContent);
				}
			}
	//选择显示修改时间
		//获取文件夹修改时间
			if (size($FoldersName) != 0 )
			{
				for ($i=0; $i<size($FoldersName); $i++) 
				{
					string $FoldersNameTmp[] = getFileTimes(($InputPath + "/" + $FoldersName[$i]));
					$textScrollListModificationTimes[$i] = $FoldersNameTmp[1];
				}
			}
		//获取各类文件修改时间
			for ($i=1; $i<size($CategoryName); $i++)
			{
				string $getCategoryOnlyName[] = stringToStringArray(`button -q -label ("FileCategory" + $i)`, "(");
				if ($getCategoryOnlyName[0] == "未知")
				{
					string $Unknown[] = `getFileList -folder $InputPath -filespec "*."`;
					$Unknown = getStringArrayDifference($Unknown, getFoldersInDirectory($InputPath));
					for ($a=0; $a<size($Unknown); $a++) 
					{
						string $textScrollListModificationTimesTmp[] = getFileTimes(($InputPath + "/" + $Unknown[$a]));
						$Unknown[$a] = $textScrollListModificationTimesTmp[1];
					}
					$textScrollListModificationTimes = mergeStringArrays($textScrollListModificationTimes, $Unknown);
				}else
				{
					string $AddContent[] = `getFileList -folder $InputPath -filespec ("*." + $getCategoryOnlyName[0])`;
					for ($b=0; $b<size($AddContent); $b++) 
					{
						string $textScrollListModificationTimesTmp[] = getFileTimes(($InputPath + "/" + $AddContent[$b]));
						$AddContent[$b] = $textScrollListModificationTimesTmp[1];
					}
					$textScrollListModificationTimes = mergeStringArrays($textScrollListModificationTimes, $AddContent);
				}
			}
	//选择显示访问时间
		//获取文件夹访问时间
			if (size($FoldersName) != 0 )
			{
				for ($i=0; $i<size($FoldersName); $i++) 
				{
					string $FoldersNameTmp[] = getFileTimes(($InputPath + "/" + $FoldersName[$i]));
					$textScrollListAccessTimes[$i] = $FoldersNameTmp[2];
				}
			}
		//获取各类文件访问时间
			for ($i=1; $i<size($CategoryName); $i++)
			{
				string $getCategoryOnlyName[] = stringToStringArray(`button -q -label ("FileCategory" + $i)`, "(");
				if ($getCategoryOnlyName[0] == "未知")
				{
					string $Unknown[] = `getFileList -folder $InputPath -filespec "*."`;
					$Unknown = getStringArrayDifference($Unknown, getFoldersInDirectory($InputPath));
					for ($a=0; $a<size($Unknown); $a++) 
					{
						string $textScrollListAccessTimesTmp[] = getFileTimes(($InputPath + "/" + $Unknown[$a]));
						$Unknown[$a] = $textScrollListAccessTimesTmp[2];
					}
					$textScrollListAccessTimes = mergeStringArrays($textScrollListAccessTimes, $Unknown);
				}else
				{
					string $AddContent[] = `getFileList -folder $InputPath -filespec ("*." + $getCategoryOnlyName[0])`;
					for ($b=0; $b<size($AddContent); $b++) 
					{
						string $textScrollListAccessTimesTmp[] = getFileTimes(($InputPath + "/" + $AddContent[$b]));
						$AddContent[$b] = $textScrollListAccessTimesTmp[2];
					}
					$textScrollListAccessTimes = mergeStringArrays($textScrollListAccessTimes, $AddContent);
				}
			}
}

//信息显示框显示1
global proc MFBFileDisplaytextScrollList1 ( string $Display[] )
{
	textScrollList -e -removeAll MFBPathDisplaytextScrollList;
	for ( $i = 0 ; $i < size($Display); $i++)
	{
		textScrollList -e -append $Display[$i] MFBPathDisplaytextScrollList;
	}
}

//信息显示框显示2
global proc MFBFileDisplaytextScrollList2 ( string $Display[] )
{
	textScrollList -e -removeAll MFBFileDatetextScrollList;
	for ( $i = 0 ; $i < size($Display); $i++)
	{
		textScrollList -e -append $Display[$i] MFBFileDatetextScrollList;
	}
}