// 选中所有带 skinCluster 的几何体（多边形/NURBS）
select -r `ls -type "mesh" -type "nurbsSurface"`;
string $skinnedObjs[];
string $models[];
for ($obj in `ls -sl`)
{
	if (`findRelatedSkinCluster $obj` != "")
	{
		$skinnedObjs[size($skinnedObjs)] = $obj;
	}
}
for ($i=0;$i<size($skinnedObjs);$i++)
{
	string $modelsTMP[];
	$modelsTMP = `listRelatives -parent $skinnedObjs[$i]`;
	//print $modelsTMP;
	$models[$i] = $modelsTMP[0];
}
select -r $models;
print("已选中 " + size($models) + " 个蒙皮对象分别为\n");
print $models;