//加载公共函数
eval ("source \"" + `asInstallScriptLocation` + "ZSToolsBoxScripts/ALLPublicScripts.mel\"");

//窗口
global proc BOXinstall()  
{
	if (`window -exists "BOXinstallwindow"`)
	{
		deleteUI -window "BOXinstallwindow";
	}
	window -title "ZSToolsBox安装程序" -h 50 -w 300 -rtf 1 -s 0 -tlb 1 BOXinstallwindow;
		columnLayout -columnAttach both 5 -adjustableColumn true -p BOXinstallwindow BOXinstallcolumnLayout;
			separator -h 5 -style "none";
			button -c "checkNowInstallPath" -label "检查安装" -ann "检测当前安装的版本插件的目录";
			button -c "startBOXinstall_1" -label "默认安装" -ann "将安装到Maya的默认插件目录";
			button -c "startBOXinstall_2" -label "独立安装" -ann "将安装到自定义路径";
			button -c "clearScriptDirinstall" -label "清理" -ann "相当于默认安装情况下的卸载，目的为删除更新迭代中本地产生的无用文件";
			separator -h 5 -style "none";
			string $nowversionfile = `asInstallScriptLocation` + "PublicFiles/Settings/Version.set";
			string $nowversion = getFileText($nowversionfile);
			text -h 15 -label ("当前版本：" + $nowversion);
			button -bgc 0.265 0.265 0.265 -hlc 1 1 1 -h 15 -c "checkVersion" -label "最新版本：VXXXX.XX.XX.X" -ann "点击查询" newversionbutton;
			separator -h 5 -style "none" newversionseparator;
	showWindow BOXinstallwindow;  
}

//检查安装
global proc checkNowInstallPath()
{
	string $userSetupPath = `internalVar -userScriptDir` + "userSetup.mel";
	string $userSetuplines[] = getFileLines($userSetupPath);
	int $turninstall = 0;
	for ($i=0; $i<size($userSetuplines); $i++)
	{
		if (`gmatch $userSetuplines[$i] "*ZSToolsBox*"`)
		{
			string $getpath[] = stringToStringArray( $userSetuplines[$i], "\"" );
			print ("已安装路径为：" + $getpath[1] + "\n");
			$turninstall = 1;
		}
	}
	if ($turninstall != 1)
	{
		warning ("未安装过本插件！！！");
	}
}

//刷新窗口版本
global proc checkVersion()
{
	deleteUI newversionbutton;
	deleteUI newversionseparator;
	string $newversion = checkGitHubVersion("qMOJIp", "Maya-ZSToolsBox");
	button -bgc 0.265 0.265 0.265 -hlc 1 1 1 -h 15 -c "checkVersion" -label ("最新版本：" + $newversion) -p BOXinstallcolumnLayout newversionbutton;
	separator -h 5 -style "none" -p BOXinstallcolumnLayout newversionseparator;
}

//清理
global proc clearScriptDirinstall()  
{
	system ("rd \"" + `internalVar -userScriptDir` + "ZSToolsBox/" + "\" /s /q");
	string $userSetupPath = `internalVar -userScriptDir` + "userSetup.mel";
	string $userSetuplines[] = getFileLines($userSetupPath);
	cleanFile($userSetupPath);
	for ($i=0; $i<size($userSetuplines); $i++)
	{
		if (!`gmatch $userSetuplines[$i] "*ZSToolsBox*"`)
		{
			writeFile($userSetupPath, $userSetuplines[$i]);
		}
	}
	warning ("清理完毕！！！");
}

//默认安装
global proc startBOXinstall_1()  
{
	system ("copy \"" + `asInstallScriptLocation` + "\" \"" + `internalVar -userScriptDir`);
	print ("安装完成！！！\n");
	//本次maya启动插件
	eval ("source \"" + `internalVar -userScriptDir` + "ZSToolsBox/ZSToolsBox.mel\"");
	deleteUI -window "BOXinstallwindow";
}

//独立安装
global proc startBOXinstall_2()  
{
	startBOXinstall();
	print ("安装完成！！！\n");
	//本次maya启动插件
	eval ("source \"" + `internalVar -userScriptDir` + "ZSToolsBox/ZSToolsBox.mel\"");
	deleteUI -window "BOXinstallwindow";
}

global proc startBOXinstall()  
{ 
	//select -clear;
	//string $DocumentsPath;
	//python ("from pathlib import Path\nimport maya.cmds as cmds\nhome_dir = Path.home()\ncmds.optionVar(stringValue=('homeDirPath', str(home_dir)))");
	//string $DocumentsPath = `optionVar -q homeDirPath`;
	//string $scriptsPath = $DocumentsPath + "\\maya\\scripts";
	//上述位置是maya非版本插件位置
	string $scriptsPath = `internalVar -userScriptDir`;
	//获取安装包路径
	string $asInstallScriptLocation = `asInstallScriptLocation`;
	//插件名字
	string $scriptName= "ZSToolsBox";
	//安装包插件框架所在路径
	string $sourceFile = $asInstallScriptLocation + "ZSToolsBox/" + $scriptName + ".mel";
	//安装包图标文件所在路径
	string $scriptannex01File= $asInstallScriptLocation + "ZSToolsBox/ZSToolsBoxIcon";
	//安装包插件索引所在路径
	string $scriptannex02File= $asInstallScriptLocation + "ZSToolsBox/ZSToolsBoxMenu.mel";
	//安装包插件书架所在路径
	string $scriptannex03File= $asInstallScriptLocation + "ZSToolsBox/ZSToolsBoxShelf.mel";
	//安装包脚本文件所在路径
	string $scriptannex04File= $asInstallScriptLocation + "ZSToolsBox/ZSToolsBoxScripts";
	//安装包公共文件所在路径
	string $scriptannex05File= $asInstallScriptLocation + "ZSToolsBox/PublicFiles/Executables/PathCopy.exe";
	//安装包版本文件所在路径
	string $scriptannex06File= $asInstallScriptLocation + "ZSToolsBox/ZSToolsBoxVersionInformation.mel";
	//安装包插件框架所在路径转Windows路径格式
	string $windowssourceFile = toNativePath( $sourceFile );
	//安装包图标文件所在路径转Windows路径格式
	string $windowsscriptannex01File = toNativePath( $scriptannex01File );
	//安装包插件索引所在路径转Windows路径格式
	string $windowsscriptannex02File = toNativePath( $scriptannex02File );
	//安装包插件书架所在路径转Windows路径格式
	string $windowsscriptannex03File = toNativePath( $scriptannex03File );
	//安装包脚本文件所在路径转Windows路径格式
	string $windowsscriptannex04File = toNativePath( $scriptannex04File );
	//安装包公共文件所在路径转Windows路径格式
	string $windowsscriptannex05File = toNativePath( $scriptannex05File );
	//安装包版本文件所在路径转Windows路径格式
	string $windowsscriptannex06File = toNativePath( $scriptannex06File );
	//检测安装路径是否存在，不存在则创建
	//string $InstallexistsPath = dirname($sourceFile);
	string $InstallexistsPath = $scriptsPath + "ZSToolsBox/\"";
	int $Installexists = `file -exists -q $InstallexistsPath`;
	if ($Installexists == 0){
		system("mkdir \"" + $scriptsPath + "ZSToolsBox/\"" + "\"");
	}
	//判断之前是否安装过，不重复在userSetup.mel写入启动代码
		//已安装插件所在路径
	string $scriptPath = $scriptsPath + "ZSToolsBox/" + $scriptName + ".mel";
		//userSetup所在路径
	string $userSetupPath = $scriptsPath + "userSetup.mel";
		//随maya启动输入文本
	string $startaddtext = "\nsource \"" + $scriptsPath + "ZSToolsBox/" + $scriptName + ".mel\";\n";
	int $existsBOXinstall = `file -exists -q $scriptPath`;
	if (!$existsBOXinstall)
	{
		print ("无旧版文件\n");
		$startfileId=`fopen $userSetupPath "a"`;
		fprint $startfileId ( $startaddtext );
		fclose $startfileId;
	}
	//插件安装
	system ("copy \"" + $windowssourceFile + "\" \"" + $scriptsPath + "ZSToolsBox\"");
	//图标文件安装
	system("mkdir \"" + $scriptsPath + "ZSToolsBox/ZSToolsBoxIcon\"" + "\"");
	system ("copy \"" + $windowsscriptannex01File + "\" \"" + $scriptsPath + "ZSToolsBox/ZSToolsBoxIcon\"");
	//插件索引安装
	system ("copy \"" + $windowsscriptannex02File + "\" \"" + $scriptsPath + "ZSToolsBox\"");
	//插件书架安装
	system ("copy \"" + $windowsscriptannex03File + "\" \"" + $scriptsPath + "ZSToolsBox\"");
	//脚本文件安装
	system("mkdir \"" + $scriptsPath + "ZSToolsBox/ZSToolsBoxScripts\"" + "\"");
	system ("copy \"" + $windowsscriptannex04File + "\" \"" + $scriptsPath + "ZSToolsBox/ZSToolsBoxScripts\"");
	//公共文件安装
	system("mkdir \"" + $scriptsPath + "ZSToolsBox/PublicFiles\"" + "\"");
	system ("copy \"" + $windowsscriptannex05File + "\" \"" + $scriptsPath + "ZSToolsBox/PublicFiles\"");
	//版本文件安装
	system ("copy \"" + $windowsscriptannex06File + "\" \"" + $scriptsPath + "ZSToolsBox\"");
	deleteUI -window "BOXinstallwindow";
}


//获取当前所在路径
global proc asInstallScriptLocator (){}

global proc string asInstallScriptLocation ()
{
string $whatIs=`whatIs asInstallScriptLocator`;
string $fullPath=`substring $whatIs 25 999`;
string $buffer[];
string $slash="/";
if (`gmatch $whatIs "*\\\\*"`)//sourced from ScriptEditor
	$slash="\\";
int $numTok=`tokenize $fullPath $slash $buffer`;
int $numLetters=size($fullPath);
int $numLettersLastFolder=size($buffer[$numTok-1]);
string $scriptLocation=`substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
return $scriptLocation;
}

BOXinstall;